config/routes.rb
Rails.application.routes.draw do

  root to: 'static#hello'

  resources :tasks
  resources :users, except: [:index]
  resources :sessions, only: [:create, :destroy]

end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :user
	validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :tasks

	include ActiveModel::SecurePassword::InstanceMethodsOnActivation
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  private
  # Confirms a logged-in user.
  def logged_in_user
    unless logged_in?
      redirect_to root_url
    end
  end

  private
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    #find our user
  	@current_user = User.find_by_email(params[:sessions][:email].downcase)

    # If the user exists AND the password entered is correct
    if @current_user and @current_user.authenticate(params[:sessions][:password])
      log_in(@current_user)
      redirect_to tasks_path
    else
      reset_session
      @current_user = nil
      redirect_to root_path
    end
  end

  def destroy
    reset_session
    @current_user = nil
    redirect_to root_path
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController

  def hello
    render :file => 'static/hello.html.erb'
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	before_action :logged_in_user, only: [:create, :destroy]

	def index
			@tasks = Task.where :user_id => session[:user_id]
	end

	def new
		@task = Task.new
	end

	def create
		@task = current_user.tasks.build(task_params)
		@task.save
		redirect_to tasks_path
	end

	def edit
    @task = Task.find(params[:id])
  end

  def update
  	@task = Task.find(params[:id])
  	@task.update(task_params)
  	redirect_to tasks_path
  end

	def destroy
		@task = Task.find(params[:id])
		@task.destroy

		redirect_to tasks_path
	end

	private
	def task_params
		params.require(:task).permit(:title, :note, :completed)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
	end

	def create
		@user = User.create(user_params)
    	if @user.save
      		session[:user_id] = @user.id
      		redirect_to tasks_path
    	else
      		redirect_to root_path
		end
	end

	private

	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  #log in user
  def log_in(current_user)
    session[:user_id] = current_user.id
    session[:user_name] = current_user.name
  end

  #find current_user
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= javascript_include_tag "application"%>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="icon" href="../../favicon.ico">
	  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
 	  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css">
    <%= stylesheet_link_tag    "application", media: "all"%>
  	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>

    <title>Todo with Bootstrap</title>
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%=link_to 'Todo App [iridakos.com]', root_path, class: 'navbar-brand'%>
        </div>

      <% if logged_in? == false %>
        <div id="navbar" class="navbar-collapse collapse">
        <%= simple_form_for :sessions, :url => sessions_path do |login| %>
          <form class="navbar-form navbar-right">
            <div class="navbar-form navbar-right">
              <%= login.submit "Sign In", class: "btn btn-primary"%>
            </div>
            <div class="navbar-form navbar-right">
              <%= login.input :password, label: false, placeholder: "Password", :input_html => {:class => 'form-control', :style=> 'width: 200px'} %>
            </div>
            <div class="navbar-form navbar-right">
              <%= login.input :email, label: false, placeholder: "Email", :input_html => {:class => 'form-control', :style=> 'width: 200px'} %>
            </div>
            <div class="navbar-form navbar-right">
              <%=link_to 'Sign up', new_user_path, class: 'btn btn-primary' %>
            </div>
          </form>
        <% end %>
      <% else %>
        <%= simple_form_for :sessions, :url => sessions_path do |login| %>
          <form class="navbar-form navbar-right">
            <div class="navbar-form navbar-right">
              <%=link_to 'Sign Out', root_path, :method => :delete, class: 'btn btn-primary' %>
            </div>
          </form>
        <% end %>
      <% end %>
        </div><!--/.navbar-collapse -->
      </div>
    </nav>

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <% if logged_in? == true %>
      <div class="container">
        <h1>Hello <%= session[:user_name] %>.</h1>
        <p></p>
        <p>
        <p><%=link_to 'New task', new_task_path, class: 'btn btn-primary btn-lg' %>
      </div>
      <% else %>
      <div class="container">
        <h1>Hello.
        <p></p>
        <p>
        <p>
      </div>
      <% end %>
    </div>

      <%= yield %>
      <hr>



      <footer>
        <p></p>
      </footer>
    </div> <!-- /container



    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
  </body>
</html>

app/views/tasks/_task_form.html.erb
<div class="container">
  <div class="form-group">
  <h2>Add Task</h2>

  <%= simple_form_for @task do |f| %>
    <div class="form-group">
      <label>Title</label>
      <%= f.input :title, label: false, :input_html => {:maxlength => 30, :style=> 'width: 450px'}%>
    </div>
    <div class="form-group">
      <label>Notation</label>
      <%= f.input :note, label: false, :input_html => {:maxlength => 400, :style=> 'width: 450px'}%>
    </div>
    <div class="form-group">
      <div class="checkbox">
        <%= f.label :completed do %>
          <%= f.check_box :completed %>
          <span class="cr"><i class="cr-icon fa fa-check"></i></span>
          <b>Completed?</b>
        <% end %>
      </div>
    </div>

    <div class="form-group">
      <%= f.button :submit, class: "btn btn-primary"%>
    </div>
  <% end %>
  </div>

</div>

app/views/tasks/edit.html.erb
<div>
	<%= render "task_form" %>
</div>

app/views/tasks/index.html.erb
<div class="container">
<div class="panel panel-default">

  <!-- Table -->
  <table class="table table-bordered">
  		<thead class="thead-inverse">
   		<tr>
		<th>Title</th>
	  	<th>Task</th>
	  	<th>Created</th>
	  	<th>Complete</th>
	  	</tr>
	  	</thead>
  	<% if @tasks.empty? %>
	    <tr>
		<td>No Tasks</td>
	  	<td></td>
	  	<td></td>
	  	<td></td>
	  	</tr>
 	<% else %>
 		<% @tasks.each do |x| %>
			<tr>
			<td><%=x.title%></td>
			<td><%=x.note%></td>
			<td><%=x.created_at.localtime.strftime("%A %d %I:%M%p")%></td>
			<% if x.completed == true %>
				<td>  
					<div class="checkbox">	
                	<span class="cr"><i class="cr-icon fa fa-check"></i></span><%=x.updated_at.to_date%>
        			</div>
				</td>
			<% else %>
				<td></td>
			<% end %>
			<td><%= link_to 'edit', edit_task_path(x) %></td>
			<td><%= link_to('delete', task_path(x), :method => :delete) %></td>
			</tr>
		<% end %>
	<% end %>
  </table>

</div>
</div>

app/views/tasks/new.html.erb
<div>
	<%= render "task_form" %>
</div>

app/views/tasks/show.html.erb
<div class="container">
<div class="panel panel-default">

  <!-- Table -->
  <table class="table table-bordered">
  		<thead class="thead-inverse">
   		<tr>
		<th>Title</th>
	  	<th>Task</th>
	  	<th>Created</th>
	  	<th>Complete</th>
	  	</tr>
	  	</thead>
  	<% if @tasks.empty? %>
	    <tr>
		<td>No Tasks</td>
	  	<td></td>
	  	<td></td>
	  	<td></td>
	  	</tr>
 	<% else %>
 		<% @tasks.each do |x| %>
			<tr>
			<td><%=x.title%></td>
			<td><%=x.note%></td>
			<td><%=x.created_at.localtime.strftime("%A %d %I:%M%p")%></td>
			<% if x.completed == true %>
				<td>  
					<div class="checkbox">	
                	<span class="cr"><i class="cr-icon fa fa-check"></i></span><%=x.updated_at.to_date%>
        			</div>
				</td>
			<% else %>
				<td></td>
			<% end %>
			<td><%= link_to 'edit', edit_task_path(x) %></td>
			<td><%= link_to('delete', task_path(x), :method => :delete) %></td>
			</tr>
		<% end %>
	<% end %>
  </table>

</div>
</div>

app/views/users/_user_form.html.erb
<div class="container">
  <div class="form-group">
  <h2>New User</h2>
  <%= simple_form_for @user do |f| %>

    <div class="form-group">
      <label>Name</label>
      <%= f.input :name, label: false, :input_html => {:maxlength => 255, :style=> 'width: 450px'}%>
    </div>

    <div class="form-group">
      <label>Email</label>
      <%= f.input :email, label: false, :input_html => {:maxlength => 255, :style=> 'width: 450px'}%>
    </div>

    <div class="form-group">
      <label>Password</label>
      <%= f.input :password, label: false, :as => :password, :input_html => {:maxlength => 255, :style=> 'width: 450px'} %>
    </div>

    <div class="form-group">
      <label>Confirm Password</label>
      <%= f.input :password_confirmation, label: false, :as => :password, :input_html => {:maxlength => 255, :style=> 'width: 450px'} %>
    </div>

    <div class="form-group">
            <%= f.button :submit, class: "btn btn-primary"%>
    </div>


  <% end %>
  
  </div>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div>
	<%= render "user_form" %>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>